services:
  - type: web
    name: youtube-downloader-bot
    env: python
    buildCommand: |
      apt-get update -qq
      apt-get install -y ffmpeg aria2
      pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SAVE_DIR
        value: /tmp/downloads
      - key: PORT
        value: 10000
